# Generated by Django 5.0.6 on 2024-07-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(max_length=10, unique=True)),
                ("status", models.CharField(max_length=20)),
                ("gate", models.CharField(max_length=5)),
                ("departure_time", models.DateTimeField()),
            ],
        ),
    ]
